apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-app-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-web-app-php
  template:
    spec:
      containers:
      - name: php-fpm
        env:
        - name: APP_ENV
          value: "prod"
        - name: APP_DEBUG
          value: "false"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "100m"
