apiVersion: v1
kind: Service
metadata:
  name: k8s-web-app-php-service
  namespace: k8s-web-app-php-dev
spec:
  selector:
    app: k8s-web-app-php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP