# service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-web-app-php
  labels:
    app: k8s-web-app-php
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: k8s-web-app-php
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
