# service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app
  labels:
    app: app
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
