apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-app-php
spec:
  selector:
    matchLabels:
      app: k8s-web-app-php
  replicas: 1
  template:
    spec:
      containers:
        - name: php-fpm
          env:
            - name: APP_ENV
              value: "dev"
            - name: APP_DEBUG
              value: "true"